#=========================================#
# Plugin Custom NPC Made By HighestDreams #
#=========================================#
# Cool Down message for when the player has reached the maximum NPC hit limit (Will send as popup).
cooldown-message: "§l§cPlease wait {seconds} seconds."
# NPC rotation distance ( 7 = When player walking around npc less than 5 block distance ).
rotation-distance: 7
# Select your language for plugin (Note: The language will only change for who is setting the NPC in).
# En (English)
# Ru (Russian)
# Ge (Germany)
# Ch (Chinese)
# Je (Japanese)
# Ko (Korean)
# Fr (French)
language: "En" # Not sensitive to uppercase and lowercase letters!
# Set a timer for NPCs to do emotes ( 10 = every 10 seconds those NPCs have emotes will do emote ).
emote-timer: 10
